ez_learn/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
    path('hello/', views.say_hello, name='say_hello' ),
    #main
     path('', views.main, name='main'),
    #learners
    path('l_login/', views.learner_login, name='learner_login'),
    path('l_register/', views.register_learner, name='register_learner'),
    path('otp/', views.otp_view, name='otp'),
    path('validate_lregistration/', views.valdate_lregistration, name='validate_lregistration'),
    path('complete_profile/<int:id>',views.complete_profile ,name='complete_profile'),
    path('learner_profile/<int:id>', views.learner_profile, name='learner_profile'),
    path('logout/', views.leaner_logout, name='logout'),

    #developer
    path('d_login/', views.developer_login, name='developer_login'),
    path('d_register/', views.register_developer, name='register_developer'),
    path('dotp/', views.developer_otp_view, name='dotp'),
    path('validate_dregistration/', views.valdate_dregistration, name='validate_dregistration'),
    path('d_home/<int:id>', views.developer_home, name='developer_home'),
    path('learner_list/<int:id>', views.learners_list, name='learners_list'),
    path('courses_list/<int:id>', views.courses_list, name='courses_list'),
    path('quiz_list/<int:id>', views.quiz_list, name='quiz_list'),
    path('add_course/<int:id>', views.add_course, name='add_course' ),
    path('delete_course/<int:id>/<int:did>', views.delete_course, name='delete_course'),
    path('create_quiz/<int:id>', views.quiz_creation_view, name='create_quiz'),
    path('delete_quiz/<int:id>/<int:did>', views.delete_quiz, name='delete_quiz'),
    path('developer_logout', views.developer_logout, name='d_logout'),

    #regarding courses
    path('home/<int:id>', views.home, name='home'),
    path('inside_course/<int:id>/<int:cid>', views.course_content, name='learn_course'),
    
    #payments
    path('check_payment/<int:id>/<str:name>', views.check_payment, name='check_payment'),
    path('making_payment/<int:id>', views.making_payment, name='making_payment'),
    path('confirm_payment/<int:id>/<int:lid>', views.confirm_payment, name='confirm_payment'),
    path('verify', views.verify, name='verify'),

    #regarding Quiz
    path('get_quiz/<str:title>/<int:id>/', views.get_into_quiz, name='get_quiz' ),
    path('quiz/<str:title>/<int:id>/', views.take_quiz_view, name='take_quiz'),

    #compiler
    path('run/<int:id>', views.runcode, name='runcode'),
    path('index/<int:id>', views.index, name='index'),

    #certification
    path('get_certificate/<int:id>/<int:cid>', views.get_certificate, name='get_certificate'),

    #others
    path('count', views.choices, name='choices'),
    #query
    path('query/<int:id>', views.query, name='query'),


]

ez_learn_project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ez_learn/', include('ez_learn.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ez_learn/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Learner(models.Model):
        username = models.CharField(max_length=50)
        first_name = models.CharField(max_length=50, default='')
        last_name = models.CharField(max_length=50, default='')
        profile_picture = models.ImageField(null=True, blank=True, upload_to='images/', default='static/dummy.png')
        email = models.EmailField()
        ph_number = models.CharField(max_length=15, blank=True, null=True)
        DOB = models.DateField( null = True, default='2001-01-01')
        user = models.OneToOneField(User, on_delete=models.CASCADE, default=None)
        dno = models.CharField(max_length=100, null=True, blank=True, default='--')
        street = models.CharField(max_length=100, null=True, blank=True, default='--')
        city = models.CharField(max_length=100, null=True, blank=True, default='--')
        state = models.CharField(max_length=100, null=True, blank=True, default='--')
        country = models.CharField(max_length=100, null=True, blank=True, default='--')
        pincode = models.CharField(max_length=100, null=True, blank=True, default='--')
        
        def __str__(self):
                return f'{self.username}'
        
class Developer(models.Model):
        developer_name = models.CharField(max_length=50)
        email = models.EmailField()
        user = models.OneToOneField(User, on_delete=models.CASCADE , default=None)

        def __str__(self):
                return f'{self.developer_name}'
        

class Course(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    price = models.IntegerField()
    discount = models.IntegerField( null=True, blank=True)

    def __str__(self):
         return f'{self.name}'


class learnings(models.Model):
    learner = models.ForeignKey(Learner, on_delete=models.CASCADE, default=None)
    course_learning = models.ForeignKey(Course, on_delete=models.CASCADE, default=None)
    activation = models.BooleanField(default=False, null=True, blank=True)

    def __str__(self):
          return f'{self.learner}'


class Quiz(models.Model):
    title = models.CharField(max_length=255)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.title


class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    question_number = models.IntegerField()
    question = models.CharField(max_length=255)

    def __str__(self):
        return self.question


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice = models.CharField(max_length=255)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.choice
    
class Submission_quiz(models.Model):
    Learner = models.ForeignKey(Learner, on_delete=models.CASCADE)
    Quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE )
    score = models.IntegerField(blank=True, null=True, default = 0)

    def __str__(self):
        return self.Learner.username
     
    
class Payment(models.Model):
    order_id = models.CharField(max_length=300, null=True, blank= True)
    payment_id = models.CharField(max_length=300, null=True, blank=True)
    status = models.BooleanField(default=False)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    learner = models.ForeignKey(Learner, on_delete=models.CASCADE)


    def __str__(self):
         return self.order_id



class Query(models.Model):
    learner = models.ForeignKey(Learner, on_delete=models.CASCADE)
    topic = models.CharField(max_length=200, null=True, blank=True)
    query = models.CharField(max_length=2000, null=True, blank=True)

    def __str__(self):
         return self.query

ez_learn/forms.py
from django import forms
from .models import Learner

class imageForm(forms.Form):
    profile_picture = forms.ImageField()

ez_learn/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.core.mail import send_mail
import math
import random
from django.contrib.auth.models import User, Group
from .models import Learner,learnings, Course, Choice, Question, Quiz, Payment, Submission_quiz, Query
from .models import Developer as D
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
import razorpay
from ez_learn_project.settings import KEY_ID,KEY_SECRET
from django.views.decorators.csrf import csrf_exempt
from .forms import imageForm
import sys
from django.template.loader import get_template
from xhtml2pdf import pisa


# Create your views here.

#saying hello (for basic configuration)

def say_hello(request):
    return HttpResponse(f'<h1>Hello how are welocome to my project of ez_learn <h1>')

#generating otp
def generateOTP():
    digits = "0123456789"
    OTP = ""
    for i in range(6) :
        OTP += digits[math.floor(random.random() * 10)]
    return OTP

#sending main while logged in
def sending_mail(message, otp, email):
    if otp != '':
        send_mail("Regarding OTP", f'{message} {otp}', "somasekhar_devisetty3@gmail.com",[email])
    else:
        send_mail("Hello learner", f'{message}', "somasekhar_devisetty3@gmail.com",[email])

#compiler functions
def index(request, id):
    learner = Learner.objects.get(id=id)
    return render(request, 'compiler/pycompiler.html', {'learner':learner})


def runcode(request, id):
    learner = Learner.objects.get(id=id)
    if request.method == "POST":
        codeareadata = request.POST['codearea']
        try:
            orig_stdout = sys.stdout
            sys.stdout = open('file.txt', 'w')
            exec(codeareadata)
            sys.stdout.close()
            sys.stdout=orig_stdout
            output = open('file.txt', 'r').read()
        except Exception as e:
            sys.stdout=orig_stdout
            output = e
    return render(request , 'compiler/pycompiler.html', {"code":codeareadata , "output":output, 'learner':learner})



def main(request):
    return render(request, 'main_template.html')



# funtion for registering a learner (from here)
def register_learner(request):
    if request.method == 'POST':
        request.session['username'] = request.POST['username']
        request.session['firstname'] = request.POST['firstname']
        request.session['lastname'] = request.POST['lastname']
        request.session['email'] = request.POST['email']
        request.session['password'] = request.POST['password']
        request.session['otp'] = generateOTP()
        print(request.session['otp'])
        message = 'your otp to complete the registration of ez_learn is '
        print(message)
        sending_mail(message, request.session['otp'], request.session['email'])
        sending_mail(message, request.session['otp'], request.session['email'])
        return redirect('otp')
    return render(request, 'learner_register.html')

#showing otp template
def otp_view(request):
    return render(request, 'otp.html')

#validating registered details
def valdate_lregistration(request):
    context = {}
    if request.method == 'POST':
        entered_otp = request.POST['otp']
        try:
            if entered_otp == request.session['otp']:
                print('somu')
                username= request.session['username']
                firstname = request.session['firstname']
                lastname = request.session['lastname']
                email = request.session['email']
                password = request.session['password']
                user = User.objects.create_user(username = username , password = password)
                print('hii')
                learner_ = Learner.objects.create(username = username, first_name= firstname, last_name = lastname, email = email, user = user)
                print('somu')
                courses = Course.objects.all()
                print(courses)
                print(learner_)
                for course in courses:
                    c = Course.objects.get(id = course.id)
                    print(c)
                    print(course)
                    learning = learnings(learner= learner_, course_learning= c, activation= False)
                    learning.save()
                print('somu')
                return render(request, 'learner/successful.html' ,{'learner' : learner_})
            else:
                context['error_message'] = 'enter valid otp'
        except:
            error = 'Username already exist'
            return render(request, 'learner_register.html', {'error': error})
    return render(request, 'otp.html', context)


#complete profile
def complete_profile(request, id):
    learner = Learner.objects.get(id=id)
    if request.method == 'GET':
        print(learner)
        form = imageForm()
        print(form)
        return render(request, 'personal.html', {'learner':learner, 'form': form})
    if request.method == 'POST':
        form = imageForm(request.POST, request.FILES)
        if form.is_valid():
            img = form.cleaned_data.get('profile_picture')
            print(img)
            learner.dno = request.POST.get('house_no')
            learner.street = request.POST.get('street')
            learner.city = request.POST.get('city')
            learner.state = request.POST.get('state')
            learner.country = request.POST.get('country')
            learner.pincode = request.POST.get('pincode')
            learner.ph_number= request.POST.get('phone_no')
            learner.DOB = request.POST.get('dob')
            learner.profile_picture = img
            learner.save()
            return redirect('learner_login')
        


#learner login function
def learner_login(request):
    context = {}
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        u = authenticate(username= username , password = password)
        if u is not None:
            learner = Learner.objects.get(user = u)
            email = learner.email
            message = 'you just logged into you ezlearn account'
            sending_mail(message,'',email)
            login(request, u)
            courses = Course.objects.all()
            return redirect('home' , learner.id)
        else:
            context['error'] = 'wrong username or password'
    return render(request, 'learner_login.html', context)


# home page of learner
@login_required
def home(request, id):
    learner = Learner.objects.get(id=id)
    courses = Course.objects.all()
    return render(request, 'learner/home.html', {
                                                        'learner': learner,
                                                        'courses' : courses 
                                                        })

def highest_score(request, id):
    pass


#getting learners personal details
def learner_profile(request, id):
    learner = Learner.objects.get(id =id)
    return render(request, 'learner/profile.html', {'learner' : learner})


#getting into particular course
def course_content(request, id, cid):
    learner = Learner.objects.get(id = id)
    course = Course.objects.get(id = cid)
    if course.name == 'PYTHON':
        if request.method == 'POST':
            if request.POST.get('basics') == 'basics':
                return render(request, 'courses/python/basics.html', {'learner': learner, 'course': course})
            if request.POST.get('intermediate') == 'intermediate':
                return render(request, 'courses/python/intermediate.html', {'learner': learner, 'course': course})
            if request.POST.get('advanced') == 'advanced':
                return render(request, 'courses/python/advanced.html', {'learner': learner, 'course': course})
        return render(request, 'courses/python/open.html', {'learner': learner, 'course': course})
    elif course.name == 'HTML':
        if request.method == 'POST':
            if request.POST.get('basics') == 'basics':
                return render(request, 'courses/html/basics.html', {'learner': learner, 'course': course})
            if request.POST.get('intermediate') == 'intermediate':
                return render(request, 'courses/html/intermediate.html', {'learner': learner, 'course': course})
            if request.POST.get('advanced') == 'advanced':
                return render(request, 'courses/html/advanced.html', {'learner': learner, 'course': course})
        return render(request, 'courses/html/open.html', {'learner': learner, 'course': course})
    elif course.name == 'CSS':
        if request.method == 'POST':
            if request.POST.get('basics') == 'basics':
                return render(request, 'courses/css/basics.html', {'learner': learner, 'course': course})
            if request.POST.get('intermediate') == 'intermediate':
                return render(request, 'courses/css/intermediate.html', {'learner': learner, 'course': course})
            if request.POST.get('advanced') == 'advanced':
                return render(request, 'courses/css/advanced.html', {'learner': learner, 'course': course})
        return render(request, 'courses/css/open.html', {'learner': learner, 'course': course})




#getting quizes layed by the particular persona
def get_into_quiz(request, title, id):
    learner = Learner.objects.get(id=id)
    course = Course.objects.get(name=title)
    quiz = Quiz.objects.get(course=course)
    try:
        submissions = Submission_quiz.objects.filter(Learner= learner,  Quiz  = quiz)
        return render(request, 'quiz/quizs_played.html', {'learner':learner, 'course' : course, 'submissions': submissions})
    except:
        return render(request, 'quiz/quizs_played.html', {'learner':learner, 'course' : course})


@login_required
def take_quiz_view(request, title, id):

ez_learn/templates/quiz/create_quiz.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'personal.css' %}">
    <style>
        .form-group input{
            margin-top: 7px;
            border-width: 2px;
            border-color: blue;
            background-color: lightblue;
        }
    </style>
</head>
<body>
            <!-- quiz/templates/quiz/create_quiz.html -->

<div style="display: flex;justify-content: center;align-items: center;flex-direction: column;">
    <h1>Create Quiz</h1>
<div class="container" style="width:70vw;margin-left: 0;margin-top: 10px;">

<form action="{% url 'create_quiz' developer.id %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="cars">Choose a Course:</label>
    <select name="course_id" id="">
        {% for course in courses %}
        <option value="{{course.id}}">{{course.name}}</option>
        {% endfor %}
  </select>
    </div>
    <div class="form-group">
    <label for="title">Quiz Title:</label>
    <input style="width: 150px;margin-bottom: 10px;" type="text" id="title" name="title" required>
    <br>
    {% for i in q_range %}
        <h3>{{i}} . question</h3>
        <input type="text" placeholder="entr question number"><br>
        <input type="text"  placeholder="enter question" name="question" required>
        <br>
        {% for j in c_range %}
            <input type="text" name="choice" required placeholder="enter option {{j}}">
            <input type="checkbox" name="correct_choice" value="{{j}}" >
            <br>
        {% endfor %}
        <br>
    {% endfor %}
    </div>
    <div class="form-group">
    <input type="submit" value="Create Quiz">
    </div>
</form>
</div>
</div>
</body>
</html>

ez_learn/templates/quiz/no_quiz_taken.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'quiz_played.css' %}">
    <title>Document</title>
</head>
<body>
    <header>
        <div class="nav">
            <div class="logo">
                <img src="{% static 'f_logo.png' %}" alt="Logo" style="width:70%;height: 70px;">
            </div>
            <div class="profile">
                <h3 class="name">{{learner.username}}</h3>
                <a href="{% url 'learner_profile' learner.id %}"><img src="{{learner.profile_picture.url}}" alt="image not Found"></a>
            </div>
        </div>
    </header>
    <div style="padding-top: 150px;display: flex;justify-content: center;align-items: center;text-align: center;flex-direction: column;">
        {% if submissions %}
        <h2 style="position: sticky;left: 0;">previous attemps</h2>

        <ol >
            {% for submission in submissions %}
            <li>
                <div class="quiz_list">
                    <h4>Score</h4>
                    <h4>:</h4>
                    <h4>{{submission.score}}</h4>
                </div>
            </li>
            {% endfor %}
        </ol>
        {% endif %}

        {% if error %}
            <h3 style="color: red;">{{error}}</h3>
        {% endif %}
    <div id="quiz-container">
        <h2>Quiz Rules:</h2>
        <ol>
            <li>Each quiz contains 20 questions.</li>
            <li>Once you start the quiz and you cannot pause or reset it.</li>
            <li>You cannot skip any question; you must answer each question before proceeding to the next.</li>
            <li>Your final score will be displayed at the end of the quiz.</li>
            <li>Have fun and test your knowledge!</li>
        </ol>
        <form action="{% url 'take_quiz' course.name learner.id %}" method="get">
            {% csrf_token %}
            <input type="submit"  value='Play Quiz' id="btn">
        </form>
        <h1><a href="{% url 'home' learner.id %}">Home</a></h1>
    </div>
</div>
</body>
</html>

ez_learn/templates/quiz/quizs_played.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'quiz_played.css' %}">
    <title>Document</title>
</head>
<body>
    <header>
        <div class="nav">
            <div class="logo">
                <img src="{% static 'f_logo.png' %}" alt="Logo" style="width:70%;height: 70px;">
            </div>
            <div class="profile">
                <h3 class="name">{{learner.username}}</h3>
                <a href="{% url 'learner_profile' learner.id %}"><img src="{{learner.profile_picture.url}}" alt="image not Found"></a>
            </div>
        </div>
    </header>
    <div style="padding-top: 150px;display: flex;justify-content: center;align-items: center;text-align: center;flex-direction: column;">
        {% if submissions %}
        <h2 style="position: sticky;left: 0;">previous attemps</h2>

        <ol >
            {% for submission in submissions %}
            <li>
                <div class="quiz_list">
                    <h4>Score</h4>
                    <h4>:</h4>
                    <h4>{{submission.score}}</h4>
                </div>
            </li>
            {% endfor %}
        </ol>
        {% endif %}
        
    <div id="quiz-container">
        <h2>Quiz Rules:</h2>
        <ol>
            <li>Each quiz contains 20 questions.</li>
            <li>Once you start the quiz and you cannot pause or reset it.</li>
            <li>You cannot skip any question; you must answer each question before proceeding to the next.</li>
            <li>Your final score will be displayed at the end of the quiz.</li>
            <li>Have fun and test your knowledge!</li>
        </ol>
        <form action="{% url 'take_quiz' course.name learner.id %}" method="get">
            {% csrf_token %}
            <input type="submit"  value='Play Quiz' id="btn">
        </form>
        <h1><a href="{% url 'home' learner.id %}">Home</a></h1>
    </div>
</div>
</body>
</html>

ez_learn/templates/quiz/result.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'takequiz.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>Document</title>
    <style>
      .dropdown-btn {
            background-color:rgb(218, 76, 218);
            color: white;
            height:fit-content;
            padding: 10px 30px;
            margin: 10px;
            border-radius: 200px;
            border: none;
            cursor: pointer;

        }
      .button {
    display: block;
    width: 115px;
    height: 45px;
    background: #4E9CAF;
    padding: 10px;
    text-align: center;
    border-radius: 5px;
    color: white;
    font-weight: bold;
    line-height: 25px;
}
#h1 {
      text-align: center;
      margin-bottom: 20px;  
    }
    
    .score {
      font-size: 24px;
      text-align: center;
      margin-top: 30px;
    }
    
    .correct {
      color: green;
      font-weight: bold;
    }
    
    .incorrect {
      color: red;
      font-weight: bold;
    }
    </style>
</head>
<body>
  <header >
    <div class="nav">      
      <div class="logo">
        <img src="{% static 'f_logo.png' %}" alt="Logo" style="width:70%;height: 70px;">
      </div>
      <div class="profile">
        <h6 class="name" ><a class="dropdown-btn" style="color: black;background-color: coral;" href="{% url 'home' learner.id %}">HOME</a></h6>
        <h3 class="name">{{learner.username}}</h3>

        <a href=""><img src="{{learner.profile_picture.url}}" alt="image not Found"></a>
      </div>
    </div>
  </header>
  <div class="container" style="margin-top: 100px;">
    <h1 id="h1">Quiz Results</h1>
    
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <div class="score">
          <p>Total : <span class="correct">{{score}}</span></p>
          <a class='button' href="{% url 'home' learner.id %}">HOME</a>
        </div>
      </div>
    </div>
  </div>
  <div style="margin-bottom: 100px;margin-top: 100px;margin-left: 30px;">
    {% for result in results %}
      <h5>{{ result.question_number }} . {{ result.question_text }}</h5>
      <div style="margin-left: 15px;">
      {% for option in result.options %}
        <p>{{ option }}</p>
      {% endfor %}

      {% if result.submitted_answer == result.correct_answer %}
        <h6 style="color: green;">&nbsp;&nbsp;Your answer: &nbsp;{{ result.submitted_answer }}</h6>
      {% else %}
        <h6 style="color:red;">&nbsp;&nbsp;Your answer: &nbsp;{{ result.submitted_answer }}</h6>
      {% endif %}
      <h6 style="color: green;">&nbsp;&nbsp;Correct answer:  &nbsp;{{ result.correct_answer }}</h6>
    </div>
    {% endfor %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
</body>
</html>

ez_learn/templates/quiz/take_quiz.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'takequiz.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>
<body>

<h1>{{ quiz.title }}</h1>
<header>
    <div class="nav">      
      <div class="logo">
        <img src="{% static 'f_logo.png' %}" alt="Logo" style="width:70%;height: 70px;">
      </div>
      <div class="profile">
        <h3 class="name">{{learner.username}}</h3>
        <a href=""><img src="{{learner.profile_picture.url}}" alt="image not Found"></a>
      </div>
    </div>
</header>
<div id="questions">
  <p style="position: fixed;top: 120px;right: 20px;" id="timer">Time left: --:--</p>
<form  id="quiz-form" action="{% url 'take_quiz' quiz.title learner.id %}" method="post">
    {% csrf_token %}
    {% for question in questions %}
        <h5>{{question.question_number}} . {{ question.question }}</h5>
        {% for choice in question.choice_set.all %}
            <input type="radio" name="{{ question.id }}" value="{{ choice.id }}"> {{ choice.choice }}<br>
        {% endfor %}
        <br>
    {% endfor %}
    <input style="background-color:blue;padding: 10px;border-radius: 10px; margin-bottom: 80px;color: white;margin-top: 20px;" type="submit" value="Submit">
</form>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
<script>
  // Function to submit the quiz automatically
  function submitQuiz() {
    document.getElementById('quiz-form').submit();
  }

  // Timer logic
  function startTimer(duration, display) {
    var timer = duration;
    var minutes, seconds;

    setInterval(function () {
      minutes = parseInt(timer / 60, 10);
      seconds = parseInt(timer % 60, 10);

      minutes = minutes < 10 ? "0" + minutes : minutes;
      seconds = seconds < 10 ? "0" + seconds : seconds;

      display.textContent = "Time left: " + minutes + ":" + seconds;

      if (--timer < 0) {
        submitQuiz();
      }
    }, 1000);
  }

  window.onload = function () {
    var quizDuration = 1200; // 20 minutes in seconds (20 * 60)
    var display = document.getElementById('timer');
    startTimer(quizDuration, display);
  };
</script>
</body>
</html>